language: node_js
node_js:
- '4'
deploy:
  provider: npm
  email: mail@jojow.de
  api_key:
    secure: I2YJpDCAYJ5iLeMKVLGIpuFiCqRxbFOjrO/5zB9WdZZ0mgBpwIpFAYEQ36BUAif3aPp7sX226xHQlbkNZ3ix+qrsqHzY/eLLIv3bDNZRf8lJGnH9fxOn09SAazVw5EViMrq7KTG1fXuhUwvN8XlRJGzIei8BmkyJMA9VswxeVD4=
